name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
        submodules: recursive

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./app/gradlew

    - name: Build with Gradle
      working-directory: ./app
      run: ./gradlew assembleDebug

    - name: Archive lint results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lint-results-debug
        path: ./app/build/reports/lint-results-debug.html

    - name: Archive outputs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: outputs
        path: ./app/build/outputs/*
